name: Use repository secrets

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  use_secrets:
    name: Access secrets in the repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Print out the password!
        run: echo Your password is ${{ secrets.password }}
        


